name: Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      SECRET_KEY: ${{secrets.HEROKU_TOKEN}}

    steps:
      - uses: actions/checkout@v2
      - name: Create heroku login file credentials
        run:
          echo "machine api.heroku.com\n  login muriithited@gmail.com\n  password $SECRET_KEY\nmachine git.heroku.com\n  login muriithited@gmail\n  password $SECRET_KEY" >~/.netrc
          cat ~/.netrc
      - name: Install git
        run: sudo apt install git
      - name: Install heroku
        run: sudo wget -qO- https://toolbelt.heroku.com/install-ubuntu.sh | sh
      - name: Add heroku remote repo
        run: heroku git:remote -a stock-info-summary
      - name: Push to Heroku
        run: git push heroku
